### ISSUE TITLE
Run first baseline

### ISSUE THREAD

**Issue by tonisojandu** [mt2017-tartu-shared-task/nmt-system-F#3]

**Comment by MaksymDel** [comment]
Thank you for your issue. It helped me understand that I have to modify shared task logistic a bit.

**Comment by MaksymDel** [comment]
Hi, teams, 

we decided to change the policy regarding issues creation a bit. Now you should create **issue** only if you **have a question**. 

In contrast, if you want to create TODO item, please create a task on the project board. Note, it is important that you create tasks on the project board so we know the state of your project. It will be especially important later in the course.

I updated the corresponding pdf's in the course materials repo.

@mt2017-tartu-shared-task/imperium
@mt2017-tartu-shared-task/mali
@mt2017-tartu-shared-task/powerrangers
@mt2017-tartu-shared-task/quidditchchampions
@mt2017-tartu-shared-task/researchers
@mt2017-tartu-shared-task/toneko
@fishel @maxdel
