### ISSUE TITLE
SoftAlignments not working of attention file created by translate.py

### ISSUE THREAD

**Issue by tonisojandu** [mt2017-tartu-shared-task/nmt-system-F#5]
```
># python process_alignments.py -i accurate-hyps.en.att_debug -o web -f Nematus
Traceback (most recent call last):
  File "process_alignments.py", line 246, in <module>
    main(sys.argv[1:])
  File "process_alignments.py", line 102, in main
    ali = [l[:len(tgt)] for l in rawAli[:len(src)]]
IndexError: invalid index to scalar variable.
```

Attention file available at http://ojandu.eu/accurate-hyps.en.att_debug

**Comment by MaksymDel** [comment]
Please provide also your hyps file without attentions

**Comment by tonisojandu** [comment]
http://ojandu.eu/accurate-hyps.en

**Comment by MaksymDel** [comment]
First try to run the tool for only first three entries from attentions the file (create a new file with line 1-70 only included). 

If it works, the reason probably is that in the accurate-hyps.en file line #269 is empty (probably system just did not generate any words). Try to delete corresponding attention entry from the attentions file (or better add something like "NA" at the right place in attentions file). 

Do it for the all empty lines and try to run the tool again.

Also, we would be happy if you included original sentences indexes in your report.

**Comment by tonisojandu** [comment]
Replaced with NA, duplicated the next line and got it working. Including the fix code just in case:

```
import java.io.*;

public class Fix {

    public static void main(String[] args) throws IOException {
        BufferedReader fin = new BufferedReader(new FileReader(args[0]));
        PrintWriter fout = new PrintWriter(new FileWriter(args[1]));

        String line;
        boolean copy = false;
        while ((line = fin.readLine()) != null) {
            if(copy) {
                fout.println(line);
            }
            copy = false;
            if(line.contains("|||  |||")) {
                line = line.replace("|||  |||", "||| NA |||");
                copy = true;
            }
            fout.println(line);
        }

        fout.close();
        fin.close();
    }
}
```

Which original indexes should I include? Pre-translate files?
Relating files are also available at http://ojandu.eu/mt.zip

**Comment by MaksymDel** [comment]
Thank you for your contribution, I will send a link to this issue to the author of the tool.

As for original indexes, it would matter if you deleted empty lines. But since you replaced, just ignore this. 

I will also reference other teams here since they might have empty lines as well.

**Comment by MaksymDel** [comment]
Hi teams,

this issue is relevant for you if you have an `"IndexError: invalid index to scalar variable."` error when you try to visualize attentions.

Ignore it otherwise. 

@mt2017-tartu-shared-task/imperium
@mt2017-tartu-shared-task/mali
@mt2017-tartu-shared-task/powerrangers
@mt2017-tartu-shared-task/quidditchchampions
@mt2017-tartu-shared-task/researchers
@mt2017-tartu-shared-task/toneko
@fishel @maxdel
